# Generated by Django 4.2.4 on 2023-11-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_material_alter_student_gender_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="College", new_name="Department",),
        migrations.RenameField(
            model_name="student", old_name="college", new_name="department",
        ),
    ]
