# Generated by Django 4.2.4 on 2023-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_department_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="book", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="exam_papers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student", name="pen", field=models.BooleanField(default=False),
        ),
    ]
